1.	CREATION DE LA TABLE TBPA_QUOTA_SOMFP

CREATE TABLE TBPA_QUOTA_SOMFP
( ID_QUOTAS NUMBER NOT NULL,
QUOTAS           NUMBER(10) NOT NULL,    
PA_STRUCT_COD    VARCHAR2(100) NOT NULL,
PA_GRADE_CODE    VARCHAR2(10) NOT NULL,  
GL_EXCECODE      VARCHAR2(10) NOT NULL,  
USER_CREA        VARCHAR2(7) NOT NULL,   
DATE_CREA        DATE NOT NULL,         
USER_MODIF               VARCHAR2(7),   
DATE_MODIF               DATE,         
USER_SIGNATAIRE          VARCHAR2(7),   
DATE_SIGNATAIRE          DATE,
CONSTRAINT TBPA_QUOTAS_PK PRIMARY key (ID_QUOTAS)
)

2.	CREATION DE LA TABLE TBCE_AGT_SOMFP

CREATE TABLE TBCE_AGT_SOMFP
(CE_AGT_ID NUMBER NOT NULL,
CE_AGT_MAT     VARCHAR2(7) NOT NULL,
PA_GRADE_CODE VARCHAR2(10) NOT NULL,
GL_EXCECODE VARCHAR2(10) NOT NULL,
ETAPE_MEMBRE INT NOT NULL ,
APP_PRO VARCHAR2(1000) NULL,
APP_EXCEP VARCHAR2(1000) NULL,
USER_DRH VARCHAR2(7) NOT NULL,
DATE_DRH DATE NULL,
USER_CHEF VARCHAR2(7) NOT NULL,
DATE_CHEF DATE NULL,

CONSTRAINT TBCE_AGT_SOMFP_PK PRIMARY key (CE_AGT_ID)
)

3.	CREATION DE SEQUENCE SEQ_QUOTAS_SOMFP

create sequence SEQ_QUOTAS_SOMFP 
START WITH 1
INCREMENT BY 1;

4.	CREATION DE SEQUENCE SEQ_NUMDOSS_SOMFP

create sequence SEQ_NUMDOSS_SOMFP
START WITH 1
INCREMENT BY 1;

4.	CREATION DE SEQUENCE SEQ_AGT_SOMFP

create sequence SEQ_AGT_SOMFP
START WITH 1
INCREMENT BY 1;

5.	CREATION DE SYNONYMES

create public synonym TBPA_QUOTA_SOMFP for TBPA_QUOTA_SOMFP;
create public synonym TBCE_AGT_SOMFP for TBCE_AGT_SOMFP;
create public synonym SEQ_QUOTAS_SOMFP for SEQ_QUOTAS_SOMFP;
create public synonym SEQ_NUMDOSS_SOMFP for SEQ_NUMDOSS_SOMFP;
create public synonym SEQ_AGT_SOMFP for SEQ_AGT_SOMFP;

6.	CREATION DE 3 GRADES DANS TBPA_GRADE

insert into tbpa_grade (pa_grade_code,pa_grade_lib,pa_typeacte_code,pa_grade_ordre) values ('GR33', 'CHEVALIER DANS L''ORDRE DE MERITE',1,NULL);
insert into tbpa_grade (pa_grade_code,pa_grade_lib,pa_typeacte_code,pa_grade_ordre) values ('GR34', 'OFFICIER DANS L''ORDRE DE MERITE',1,NULL);
insert into tbpa_grade (pa_grade_code,pa_grade_lib,pa_typeacte_code,pa_grade_ordre) values ('GR35', 'COMMANDEUR DANS L''ORDRE DE MERITE',2,NULL);
insert into tbpa_grade (pa_grade_code,pa_grade_lib,pa_typeacte_code,pa_grade_ordre) values ('GR36', 'MEMBRE DE CONSEIL DE L''ORDRE DE MERITE',1,NULL);

7.	CREATION D’UNE NATURE D’ACTE

INSERT INTO TBPA_NATACTE(PA_NATACTE_CODE,PA_TYPEACTE_CODE,PA_NATACTE_LIB,PA_DIRECTION,PA_NATACTE_PRISENCOMPTE,TBPC_HABVIS_CODE,PA_NATACTE_FUR)
VALUES ('A0161',1,'NOMINATION DANS L''ORDRE DU MERITE','SOMFP',0,'P122489',0)

8.	 INSERTION D’UNE VUE DANS LA TABLE (TBGL_VU)

INSERT INTO tbgl_vu VALUES('V0161','LA LOI N° 60-403 DU 10 DECEMBRE 1960 PORTANT ORGANISATION DE L''ORDRE NATIONAL DE LA REPUBLIQUE DE COTE D''IVOIRE;', NULL, NULL, NULL, 'FIXE'):

9.	 INSERTION DE DEUX DECRET DANS LA TABLE( TBPA_DECRET)

INSERT INTO TBPA_DECRET (PA_DECRET_CODE, pa_decret_lib, pa_decret_texte, pa_decret_datesign)
values ('DEC48', 'LE DECRET N° 2012-912 DU 19 SEPTEMBRE 2012','LE DECRET N° 2012-912 DU 19 SEPTEMBRE 2012 PORTANT INSTITUTION D''UN ORDRE DU MERITE DE LA FONCTION PUBLIQUE;','19/09/2012');

INSERT INTO TBPA_DECRET (PA_DECRET_CODE, pa_decret_lib, pa_decret_texte, pa_decret_datesign)
values ('DEC97', 'LE DECRET N°2017-12 DU 10 JANVIER 2017','LE DECRET N° 2017-12 DU 10 JANVIER 2017 PORTANT NOMINATION DU PREMIER MINISTRE, CHEF DU GOUVERNEMENT ;','10/01/2017');

10.	PARAMETRAGE DES ECRANS A L’AIDE DE L’ECRAN (PARAM_ARTICLE_MAT et PARAM_VU_DECRET - voir fichier word)
11.	AJOUT DU SOMFP DANS LA TABLE TBPA_DIRECTION

 INSERT INTO TBPA_DIRECTION (PA_DIRECTION_CODE, PA_STRUCT_COD, PA_DIRECTION_LIB, PA_DIRECTION_CHAMPCOUR)
  VALUES ('DI564','S0019','SECRETARIAT DE L''ORDRE DU MERITE','SOMFP');
